import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from database import Base

# Import every model so Base.metadata (target_metadata below) is fully
# populated — required for `alembic revision --autogenerate` to see all
# tables, even though the multi-tenant migrations in this project are
# hand-written rather than autogenerated (see CLAUDE.md).
from models.tenant import Tenant  # noqa: F401
from models.servicio import Servicio  # noqa: F401
from models.paciente import Paciente  # noqa: F401
from models.usuario import Usuario  # noqa: F401
from models.cita import Cita  # noqa: F401
from models.pago import Pago  # noqa: F401
from models.venta import Venta  # noqa: F401
from models.gasto import Gasto  # noqa: F401

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Same env var + dialect rewrite as database.py — this is always the ADMIN
# connection (table owner), never APP_DATABASE_URL. Migrations need full DDL
# rights and must be able to run before RLS/app_user exist at all.
_DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://admin:password_seguro@db:5432/elysium_agenda",
)
if _DATABASE_URL.startswith("postgresql://"):
    _DATABASE_URL = _DATABASE_URL.replace("postgresql://", "postgresql+psycopg2://", 1)

config.set_main_option("sqlalchemy.url", _DATABASE_URL)


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
