"""multi-tenant schema — tenants, servicios, tenant_id on all 6 tables, composite keys

Hand-written (not autogenerated — autogenerate does not reliably detect PK
column-set changes or composite FK changes, and cannot generate the seed/
backfill DML this revision needs).

Order (matches the approved plan): create tenants+servicios -> seed the
Elysium tenant + its servicios -> add tenant_id nullable on the 6 existing
tables -> backfill -> SET NOT NULL -> drop old single-column constraints ->
create new tenant-scoped constraints -> add tenant_id indexes.

Constraint names for the *existing* single-column constraints being dropped
(pacientes_pkey, usuarios_email_key, citas_paciente_id_fkey,
citas_medico_id_fkey, pagos_paciente_id_fkey, ventas_paciente_id_fkey) were
confirmed against the running database with:

    SELECT conname, contype, conrelid::regclass FROM pg_constraint
    WHERE conrelid::regclass::text IN
        ('pacientes','usuarios','citas','pagos','ventas','gastos');

Downgrade note: this is a *time-bounded* rollback guarantee. It is only safe
to run while Elysium is the sole tenant — once a second tenant's data exists,
downgrading would either fail on a PK/unique collision (the safe outcome) or
silently merge distinct tenants' citas/pagos/ventas/gastos rows together (no
literal collision required). Do not downgrade this revision after onboarding
a second tenant.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-06

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed, not re-derived from a SELECT — reused across the tenant insert, the
# servicios seed, and every backfill UPDATE below.
ELYSIUM_TENANT_ID = "7a1c8740-8ff3-4afd-8bd7-74d5da0ce9b8"

ELYSIUM_CONFIG = {
    "vigencia_plan_dias": 45,
    "ventana_cancelacion_horas": 2,
    "horario": {
        "bloques": [
            {"inicio": "07:00", "fin": "11:00"},
            {"inicio": "14:00", "fin": "18:00"},
        ],
        "intervalo_min": 30,
        "dias_activos": [1, 2, 3, 4, 5, 6],
    },
    "sesion_cortesia": {
        "habilitada": True,
        "duracion_min": 45,
        "max_por_paciente": 1,
    },
}

# Fisioterapia is 60 min, not 30 — confirmed against services/email.py's
# existing _DURACION map and CLAUDE.md; "30 min" would be a real regression
# (that number is the slot-grid interval, which applies to both services).
# "Sesión de cortesía" has no row of its own here — it shares Pilates'
# capacidad (both are 6 today, same physical class); its duration/limit come
# from ELYSIUM_CONFIG["sesion_cortesia"] instead.
ELYSIUM_SERVICIOS = [
    {"nombre": "Pilates", "capacidad": 6, "duracion_min": 60},
    {"nombre": "Fisioterapia", "capacidad": 2, "duracion_min": 60},
]

TENANT_SCOPED_TABLES = ("pacientes", "usuarios", "citas", "pagos", "ventas", "gastos")


def upgrade() -> None:
    # ── Step A: new tables ──────────────────────────────────────────────
    op.create_table(
        "tenants",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("nombre_comercial", sa.String(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("custom_domain", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=False, server_default="America/Bogota"),
        sa.Column("branding", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("config", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("features_override", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("slug", name="tenants_slug_key"),
        sa.UniqueConstraint("custom_domain", name="tenants_custom_domain_key"),
    )

    op.create_table(
        "servicios",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("capacidad", sa.Integer(), nullable=False),
        sa.Column("duracion_min", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="servicios_tenant_id_fkey"),
        sa.UniqueConstraint("tenant_id", "nombre", name="servicios_tenant_id_nombre_key"),
    )

    # ── Step B: seed the Elysium tenant + its servicios ─────────────────
    op.execute(
        sa.text(
            """
            INSERT INTO tenants (id, slug, nombre_comercial, plan, estado, timezone, config)
            VALUES (:id, 'elysium', 'Elysium Fisio-Pilates', 'completo', 'activo',
                    'America/Bogota', CAST(:config AS jsonb))
            """
        ).bindparams(id=ELYSIUM_TENANT_ID, config=json.dumps(ELYSIUM_CONFIG))
    )

    for servicio in ELYSIUM_SERVICIOS:
        op.execute(
            sa.text(
                """
                INSERT INTO servicios (tenant_id, nombre, capacidad, duracion_min, activo)
                VALUES (:tenant_id, :nombre, :capacidad, :duracion_min, true)
                """
            ).bindparams(tenant_id=ELYSIUM_TENANT_ID, **servicio)
        )

    # ── Step C: tenant_id nullable on the 6 existing tables ─────────────
    for table in TENANT_SCOPED_TABLES:
        op.add_column(table, sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True))

    # ── Step D: backfill ─────────────────────────────────────────────────
    for table in TENANT_SCOPED_TABLES:
        op.execute(
            sa.text(f"UPDATE {table} SET tenant_id = :tenant_id").bindparams(tenant_id=ELYSIUM_TENANT_ID)
        )

    # ── Step E: SET NOT NULL ─────────────────────────────────────────────
    for table in TENANT_SCOPED_TABLES:
        op.alter_column(table, "tenant_id", nullable=False)

    # ── Step F: drop child FKs first (unblocks the parent PK/unique drops) ─
    op.drop_constraint("citas_paciente_id_fkey", "citas", type_="foreignkey")
    op.drop_constraint("citas_medico_id_fkey", "citas", type_="foreignkey")
    op.drop_constraint("pagos_paciente_id_fkey", "pagos", type_="foreignkey")
    op.drop_constraint("ventas_paciente_id_fkey", "ventas", type_="foreignkey")

    # ── Step G: drop old single-column parent constraints ───────────────
    op.drop_constraint("pacientes_pkey", "pacientes", type_="primary")
    op.drop_constraint("usuarios_email_key", "usuarios", type_="unique")

    # ── Step H: new tenant-scoped parent constraints ─────────────────────
    op.create_primary_key("pacientes_pkey", "pacientes", ["tenant_id", "Paciente"])
    op.create_foreign_key("pacientes_tenant_id_fkey", "pacientes", "tenants", ["tenant_id"], ["id"])

    op.create_foreign_key("usuarios_tenant_id_fkey", "usuarios", "tenants", ["tenant_id"], ["id"])
    op.create_unique_constraint("usuarios_tenant_id_id_key", "usuarios", ["tenant_id", "id"])
    op.create_unique_constraint("usuarios_tenant_id_email_key", "usuarios", ["tenant_id", "email"])

    op.create_foreign_key("citas_tenant_id_fkey", "citas", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key("pagos_tenant_id_fkey", "pagos", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key("ventas_tenant_id_fkey", "ventas", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key("gastos_tenant_id_fkey", "gastos", "tenants", ["tenant_id"], ["id"])

    # ── Step I: new composite child FKs ──────────────────────────────────
    op.create_foreign_key(
        "citas_tenant_id_paciente_id_fkey", "citas", "pacientes",
        ["tenant_id", "paciente_id"], ["tenant_id", "Paciente"],
    )
    op.create_foreign_key(
        "citas_tenant_id_medico_id_fkey", "citas", "usuarios",
        ["tenant_id", "medico_id"], ["tenant_id", "id"],
    )
    op.create_foreign_key(
        "pagos_tenant_id_paciente_id_fkey", "pagos", "pacientes",
        ["tenant_id", "paciente_id"], ["tenant_id", "Paciente"],
    )
    op.create_foreign_key(
        "ventas_tenant_id_paciente_id_fkey", "ventas", "pacientes",
        ["tenant_id", "paciente_id"], ["tenant_id", "Paciente"],
    )

    # ── Step J: indexes — RLS (added in 0003) filters every query by
    # tenant_id, and Postgres never auto-indexes the referencing side of a
    # FK. pacientes/usuarios already get one from their composite PK/unique
    # constraints above; servicios already has one from Step A.
    op.create_index("ix_citas_tenant_id", "citas", ["tenant_id"])
    op.create_index("ix_pagos_tenant_id", "pagos", ["tenant_id"])
    op.create_index("ix_ventas_tenant_id", "ventas", ["tenant_id"])
    op.create_index("ix_gastos_tenant_id", "gastos", ["tenant_id"])


def downgrade() -> None:
    op.drop_index("ix_gastos_tenant_id", table_name="gastos")
    op.drop_index("ix_ventas_tenant_id", table_name="ventas")
    op.drop_index("ix_pagos_tenant_id", table_name="pagos")
    op.drop_index("ix_citas_tenant_id", table_name="citas")

    # reverse of Step I (children first)
    op.drop_constraint("ventas_tenant_id_paciente_id_fkey", "ventas", type_="foreignkey")
    op.drop_constraint("pagos_tenant_id_paciente_id_fkey", "pagos", type_="foreignkey")
    op.drop_constraint("citas_tenant_id_medico_id_fkey", "citas", type_="foreignkey")
    op.drop_constraint("citas_tenant_id_paciente_id_fkey", "citas", type_="foreignkey")

    # reverse of Step H
    op.drop_constraint("gastos_tenant_id_fkey", "gastos", type_="foreignkey")
    op.drop_constraint("ventas_tenant_id_fkey", "ventas", type_="foreignkey")
    op.drop_constraint("pagos_tenant_id_fkey", "pagos", type_="foreignkey")
    op.drop_constraint("citas_tenant_id_fkey", "citas", type_="foreignkey")
    op.drop_constraint("usuarios_tenant_id_email_key", "usuarios", type_="unique")
    op.drop_constraint("usuarios_tenant_id_id_key", "usuarios", type_="unique")
    op.drop_constraint("usuarios_tenant_id_fkey", "usuarios", type_="foreignkey")
    op.drop_constraint("pacientes_tenant_id_fkey", "pacientes", type_="foreignkey")
    op.drop_constraint("pacientes_pkey", "pacientes", type_="primary")

    # reverse of Step G (recreate original single-column constraints)
    op.create_primary_key("pacientes_pkey", "pacientes", ["Paciente"])
    op.create_unique_constraint("usuarios_email_key", "usuarios", ["email"])

    # reverse of Step F (recreate original single-column FKs)
    op.create_foreign_key("citas_paciente_id_fkey", "citas", "pacientes", ["paciente_id"], ["Paciente"])
    op.create_foreign_key("citas_medico_id_fkey", "citas", "usuarios", ["medico_id"], ["id"])
    op.create_foreign_key("pagos_paciente_id_fkey", "pagos", "pacientes", ["paciente_id"], ["Paciente"])
    op.create_foreign_key("ventas_paciente_id_fkey", "ventas", "pacientes", ["paciente_id"], ["Paciente"])

    # collapses reverse of Step E/D/C: dropping the column removes NOT NULL,
    # the backfilled data, and the column itself in one statement
    for table in TENANT_SCOPED_TABLES:
        op.drop_column(table, "tenant_id")

    # reverse of Step A/B: DROP TABLE removes seeded rows + its own
    # constraints automatically; servicios must go first (FK -> tenants)
    op.drop_table("servicios")
    op.drop_table("tenants")
