"""pagos.fecha_inicio — separate the plan's start date from its payment date

Clients don't always start using a plan the same day it's fully paid (start
on the 1st, finish paying in installments by the 10th/25th/30th). Before
this revision, fecha_vencimiento was computed as fecha_pago + vigencia_dias
(routes/pagos.py:create_pago), which shortchanges real usable days whenever
payment trails the actual start. fecha_inicio is now the base for that
calculation instead; fecha_pago is unchanged (still the payment record).

Added nullable, backfilled from fecha_pago (so fecha_inicio == fecha_pago
for every existing row, keeping their already-stored fecha_vencimiento
exactly consistent with the new formula — no recompute needed), then set
NOT NULL. Not autogenerated: needs the backfill UPDATE, same reasoning as
0002/0003.

`ADD COLUMN IF NOT EXISTS` (raw SQL, not op.add_column): found via a
migration rehearsal against a copy of Elysium's real production data that
`pagos.fecha_inicio` can already exist there — an earlier commit shipped
this same column through main's hand-rolled `_run_migrations()` (raw
`ALTER TABLE ... ADD COLUMN IF NOT EXISTS`) before this Alembic revision
was ever applied anywhere, so Alembic has no record of it. Idempotent here
either way: a fresh single-tenant DB gets the column added normally, one
that already has it (with the same backfilled values) just gets skipped.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-08

"""
from typing import Sequence, Union

from alembic import op

revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE pagos ADD COLUMN IF NOT EXISTS fecha_inicio DATE")
    # Backfill must bypass RLS — same reasoning as 0005 (see its upgrade()):
    # if this migration runs as a non-superuser table owner (app_user), the
    # FORCE ROW LEVEL SECURITY from 0003 filters every row out of the UPDATE
    # (no app.tenant_id in a migration) and the SET NOT NULL below then fails.
    # In real production this step happened to pass only because pagos already
    # had fecha_inicio populated by main's old raw-SQL _run_migrations() before
    # Alembic ran — a fresh DB migrated as app_user would fail here exactly like
    # 0005 did. Dropping RLS enforcement for the backfill (restored right after)
    # makes it correct regardless of the running role; a superuser bypasses RLS
    # anyway, so this is a no-op there.
    op.execute("ALTER TABLE pagos DISABLE ROW LEVEL SECURITY")
    op.execute("UPDATE pagos SET fecha_inicio = fecha_pago WHERE fecha_inicio IS NULL")
    op.execute("ALTER TABLE pagos ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE pagos FORCE ROW LEVEL SECURITY")
    op.alter_column("pagos", "fecha_inicio", nullable=False)


def downgrade() -> None:
    op.drop_column("pagos", "fecha_inicio")
